export const GET_ALAFFICHE_MOVIES = 'GET_ALAFFICHE_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const UPDATE_MOVIE_SEANCE = 'UPDATE_MOVIE_SEANCE';
